export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS'
export const FETCH_ERROR = 'FETCH_ERROR'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_REVIEWS = 'FETCH_REVIEWS'
